runtime: custom
env: flex

# This configures the service to use the Dockerfile in the root directory.
# You can also use Cloud Run instead of App Engine Flex.

env_variables:
  GEMINI_API_KEY: "AIzaSyDHcK4UIK8ZZsGboyKvOk6RufCBNpLpmpg" # Should be set in Secret Manager in production

# Automatic scaling settings
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cool_down_period_sec: 120
  cpu_utilization:
    target_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
